import Link from "next/link";
import { ArrowUpRight, BookOpen, PenLine } from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { SectionHeader } from "@/components/ui/section";
import { Reveal } from "@/components/ui/reveal";
import { Button } from "@/components/ui/button";
import { writing } from "@/lib/content";
export const metadata = { title: "Writing & eBooks", description: "Editorial work by Joseph Unaogu — eBooks, articles, and copywriting. Writing is one of Joseph's strongest professional skills." };
export default function WritingPage() {
  const featured = writing[0]; const rest = writing.slice(1);
  const ext = (href: string | undefined) => (href && /^https?:\/\//.test(href) ? { target: "_blank", rel: "noopener noreferrer" } : {});
  return (<><PageHeader eyebrow="Ideas, Content & Curiosity" title={<>Where words do <span className="text-gradient">the heavy lifting.</span></>} description="Writing is one of my strongest areas — eBooks, articles, and copy built with structure and intent. This is the editorial side of the digital HQ." />
      <section className="relative py-8"><div className="container-px">
        <Reveal><Link href={featured.link || "#"} {...ext(featured.link)} className="group surface grid gap-6 overflow-hidden p-8 md:grid-cols-[1.4fr_0.6fr] md:p-10"><div><span className="inline-flex items-center gap-2 rounded-full bg-neon-magenta/15 px-3 py-1 text-[11px] font-medium text-neon-magenta"><BookOpen size={13} /> Featured · {featured.category}</span><h2 className="mt-4 font-display text-3xl font-semibold tracking-tighter2 text-paper sm:text-4xl">{featured.title}</h2><p className="mt-4 max-w-xl text-base leading-relaxed text-paper-muted">{featured.description}</p><span className="mt-6 inline-flex items-center gap-1.5 text-sm text-neon-magenta">{featured.link ? "Read more" : "Status: " + featured.status} <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1" /></span></div><div className="flex items-center justify-start md:justify-end"><span className="font-mono text-xs uppercase tracking-wider text-paper-dim">{featured.status}</span></div></Link></Reveal>
        <div className="mt-12"><SectionHeader eyebrow="More writing" title="Articles & drafts" description="Notes on AI tools, copywriting, and building in public — most still in draft. Updated as they develop." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rest.map((w, i) => (<Reveal key={w.id} delay={i * 0.05}><Link href={w.link || "#"} {...ext(w.link)} className="group surface flex h-full flex-col p-6 transition-all duration-300 hover:-translate-y-1 hover:border-neon-magenta/40"><span className="inline-flex items-center gap-2 text-[11px] uppercase tracking-wider text-paper-dim"><PenLine size={13} /> {w.category}</span><h3 className="mt-3 font-display text-lg font-semibold text-paper">{w.title}</h3><p className="mt-2 flex-1 text-sm leading-relaxed text-paper-muted">{w.description}</p><div className="mt-5 flex items-center justify-between"><span className="text-xs text-paper-dim">{w.status}</span><span className="inline-flex items-center gap-1 text-sm text-neon-magenta">{w.link ? "Read" : "Soon"} <ArrowUpRight size={14} className="transition-transform group-hover:translate-x-1" /></span></div></Link></Reveal>))}</div></div>
        <div className="mt-12 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/10 bg-ink-850/60 p-7"><div><h3 className="font-display text-lg font-semibold text-paper">Need writing that sounds human?</h3><p className="mt-2 text-sm text-paper-muted">eBooks, copy, and content — my most developed professional service.</p></div><Button href="/services#ebooks" variant="secondary">Explore writing services <ArrowUpRight size={15} /></Button></div>
      </div></section></>);
}