import Link from "next/link";
import { PageHeader } from "@/components/ui/page-header";
import { Reveal } from "@/components/ui/reveal";
import { Button } from "@/components/ui/button";
import { projects } from "@/lib/content";
export const metadata = { title: "Admin", robots: { index: false, follow: false } };
export default function AdminPage() {
  return (<><PageHeader eyebrow="Admin (Architecture)" title={<>Portfolio control <span className="text-gradient">center.</span></>} description="This is the admin architecture scaffold. Wire it to a CMS or database to let Joseph update content without touching source code." />
    <section className="relative py-8"><div className="container-px space-y-6">
      <Reveal><div className="surface p-7"><h3 className="font-display text-lg font-semibold text-paper">Editable content sources</h3><p className="mt-3 text-sm leading-relaxed text-paper-muted">All copy lives in <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-neon-cyan">src/lib/content.ts</code>. Moving this to a database + auth (NextAuth + Prisma/Postgres) turns every field below into an editable form.</p><ul className="mt-4 grid gap-2 text-sm text-paper-muted sm:grid-cols-2"><li>• Name & bio</li><li>• Skills & levels</li><li>• Project URLs & descriptions</li><li>• Project thumbnails (upload)</li><li>• Project status & availability</li><li>• Technologies</li><li>• Featured flags</li><li>• Writing projects</li><li>• YouTube / social links</li><li>• Current focus (Now)</li><li>• Timeline events</li><li>• Services & contact</li></ul></div></Reveal>
      <Reveal delay={0.05}><div className="surface p-7"><h3 className="font-display text-lg font-semibold text-paper">Writing & eBook management</h3><p className="mt-3 text-sm leading-relaxed text-paper-muted">Books live in <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-neon-cyan">src/lib/content.ts</code> under the <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-neon-cyan">writing</code> array. Each entry supports:</p><ul className="mt-4 grid gap-2 text-sm text-paper-muted sm:grid-cols-2"><li>• Title & subtitle</li><li>• Author</li><li>• Genre (fiction / nonfiction)</li><li>• Category & subcategory</li><li>• Detailed summary</li><li>• Key themes</li><li>• Sample excerpt</li><li>• Cover image (upload / replace)</li><li>• Additional images</li><li>• Writing status</li><li>• Featured & published flags</li></ul><p className="mt-4 text-xs text-paper-dim">An admin form would let Joseph add, edit, remove, and re-order books, upload/replace covers, and edit each summary — the Writing page and <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-neon-cyan">/writing/[id]</code> detail pages update automatically.</p></div></Reveal>
      <Reveal delay={0.1}><div className="surface p-7"><h3 className="font-display text-lg font-semibold text-paper">Project preview pipeline</h3><p className="mt-3 text-sm leading-relaxed text-paper-muted">Priority order used by the portfolio:</p><ol className="mt-3 list-decimal space-y-1.5 pl-5 text-sm text-paper-muted"><li>Real website screenshot via rendering service (automatic).</li><li>Manual uploaded screenshot (admin upload).</li><li>Custom project image.</li><li>Designed fallback (only when no URL/image exists).</li></ol><p className="mt-3 text-xs text-paper-dim">Auth-gated projects (e.g. SupportIQ) skip auto screenshots and show a "Private Preview" label until a manual screenshot is uploaded.</p></div></Reveal>
      <Reveal delay={0.1}><div className="surface p-7"><h3 className="font-display text-lg font-semibold text-paper">Manual screenshot upload (per project)</h3><p className="mt-3 text-sm leading-relaxed text-paper-muted">Set <code className="rounded bg-white/5 px-1.5 py-0.5 font-mono text-xs text-neon-cyan">previewImage</code> on a project to override the automatic screenshot. This is the field an admin upload form would write to.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{projects.map((p) => (<div key={p.id} className="flex items-center justify-between rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm"><span className="text-paper">{p.name}</span><span className={p.previewImage ? "text-neon-cyan" : "text-paper-dim"}>{p.previewImage ? "custom" : "auto"}</span></div>))}</div></div></Reveal>
      <div className="flex flex-wrap gap-3"><Button href="/projects">View live projects</Button><Link href="/" className="text-sm text-paper-muted underline-offset-4 hover:text-paper hover:underline">Back home</Link></div>
    </div></section></>);
}